version: 2

updates:
- package-ecosystem: "npm"
  directory: '/'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 2
  assignees:
    - skepfusky
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope

- package-ecosystem: "npm"
  directory: '/app'
  schedule:
    interval: weekly
    time: '00:00'
  open-pull-requests-limit: 10
  assignees:
    - skepfusky
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
